# Generated by Django 5.2.8 on 2025-12-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-created_at"]},
        ),
    ]
