# Generated by Django 5.2.8 on 2025-12-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
