# Generated by Django 5.2.8 on 2025-12-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_is_deleted_alter_blog_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={
                "verbose_name": "Blog Reaction",
                "verbose_name_plural": "Blog Reactions",
            },
        ),
        migrations.RemoveField(
            model_name="like",
            name="is_like",
        ),
        migrations.AddField(
            model_name="like",
            name="reaction",
            field=models.CharField(
                choices=[("like", "Like"), ("dislike", "Dislike"), ("none", "None")],
                default="none",
                max_length=10,
            ),
        ),
    ]
