# Generated by Django 5.2.8 on 2025-12-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_like_options_remove_like_is_like_like_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
