# Generated by Django 5.2.8 on 2025-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blog_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
